import { Transaction, FinanceStats } from './types';

export const DUMMY_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    reference: 'TXN001234',
    investor: 'Chidi Okonkwo',
    type: 'Deposit',
    amount: 2500000,
    formattedAmount: '₦2.50M',
    date: '2024-01-25',
    time: '14:30',
    status: 'Completed',
  },
  {
    id: '2',
    reference: 'TXN001235',
    investor: 'Amara Nwosu',
    type: 'Withdrawal',
    amount: 1200000,
    formattedAmount: '₦1.20M',
    date: '2024-01-25',
    time: '12:15',
    status: 'Pending',
  },
  {
    id: '3',
    reference: 'TXN001234',
    investor: 'Chidi Okonkwo',
    type: 'Deposit',
    amount: 2500000,
    formattedAmount: '₦2.50M',
    date: '2024-01-25',
    time: '14:30',
    status: 'Completed',
  },
  {
    id: '4',
    reference: 'TXN001241',
    investor: 'Fatima Yusuf',
    type: 'Withdrawal',
    amount: 2000000,
    formattedAmount: '₦2.00M',
    date: '2024-01-23',
    time: '13:20',
    status: 'Rejected',
  },
  {
    id: '5',
    reference: 'TXN001234',
    investor: 'Chidi Okonkwo',
    type: 'Deposit',
    amount: 2500000,
    formattedAmount: '₦2.50M',
    date: '2024-01-25',
    time: '14:30',
    status: 'Completed',
  },
  {
    id: '6',
    reference: 'TXN001235',
    investor: 'Amara Nwosu',
    type: 'Withdrawal',
    amount: 1200000,
    formattedAmount: '₦1.20M',
    date: '2024-01-25',
    time: '12:15',
    status: 'Pending',
  },
  {
    id: '7',
    reference: 'TXN001236',
    investor: 'Kunle Adebayo',
    type: 'Investment',
    amount: 5000000,
    formattedAmount: '₦5.00M',
    date: '2024-01-25',
    time: '10:45',
    status: 'Completed',
  },
  {
    id: '8',
    reference: 'TXN001236',
    investor: 'Kunle Adebayo',
    type: 'Yield',
    amount: 5000000,
    formattedAmount: '₦5.00M',
    date: '2024-01-25',
    time: '10:45',
    status: 'Completed',
  },
  {
    id: '9',
    reference: 'TXN001238',
    investor: 'Emeka Obi',
    type: 'Withdrawal',
    amount: 800000,
    formattedAmount: '₦0.80M',
    date: '2024-01-24',
    time: '14:10',
    status: 'Processing',
  },
  {
    id: '10',
    reference: 'TXN001241',
    investor: 'Fatima Yusuf',
    type: 'Withdrawal',
    amount: 2000000,
    formattedAmount: '₦2.00M',
    date: '2024-01-23',
    time: '14:25',
    status: 'Completed',
  },
];

// Calculate tab counts dynamically based on DUMMY_TRANSACTIONS
// export function getTabCounts() {
//   return {
//     'all-transactions': DUMMY_TRANSACTIONS.length,
//     'withdrawal-requests': DUMMY_TRANSACTIONS.filter(t => t.type === 'Withdrawal').length,
//     'reconciliation': 3,
//     'yield-events': DUMMY_TRANSACTIONS.filter(t => t.type === 'Yield').length,
//     'investors-wallet': DUMMY_TRANSACTIONS.length,
//   };
// }

export const FINANCE_STATS: FinanceStats[] = [
  {
    label: 'Total Balance',
    value: '₦42.8M',
    description: 'As of today',
    icon: 'Wallet',
    color: 'text-gray-900',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
  },
  {
    label: 'Active Wallets',
    value: '567',
    description: 'Investor wallets',
    icon: 'Users',
    color: 'text-gray-900',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-100',
  },
  {
    label: 'Total Yields Disbursed',
    value: '₦128.5M',
    description: 'Year to date',
    icon: 'TrendingUp',
    color: 'text-gray-900',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  {
    label: 'Pending Withdrawals',
    value: '₦5.5M',
    description: '3 requests',
    icon: 'Clock',
    color: 'text-gray-900',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
  },
];
