import { type YieldDisbursementLedger } from "@/interface";

export const DUMMY_YIELD_EVENT_DETAILS: YieldDisbursementLedger = {
  batchId: "YDB-12-20260201",
  eventId: "YDB-12-20260201",
  investmentId: 12,
  investmentName: "Lekki Pearl Gardens",
  totalPayout: 45000000,
  yieldRate: 4.5,
  disbursedDate: "Feb 1, 2026",
  returnsDate: "Feb 1, 2026",
  status: "partial",
  statusBreakdown: {
    pending: 2,
    disbursed: 120,
    flagged: 2,
  },
  totalParticipatingInvestors: 124,
  investors: [
    {
      disbursementId: 901,
      investorId: 901,
      investmentFundId: 88,
      disbursementCode: "YLD-PNT-102",
      investorName: "Chukwudi O.",
      amountInvested: 15000000,
      payoutAmount: 675000,
      status: "flagged",
      canFlag: false,
      canDisburse: false,
      flagReason: "Incorrect amount calculation",
      flaggedAt: "2026-02-01 10:15",
    },
    {
      disbursementId: 902,
      investorId: 902,
      investmentFundId: 88,
      disbursementCode: "YLD-PNT-103",
      investorName: "Amina K.",
      amountInvested: 20000000,
      payoutAmount: 900000,
      status: "disbursed",
      canFlag: false,
      canDisburse: false,
      flagReason: null,
      flaggedAt: null,
    },
    {
      disbursementId: 903,
      investorId: 903,
      investmentFundId: 88,
      disbursementCode: "YLD-PNT-104",
      investorName: "Bola T.",
      amountInvested: 12000000,
      payoutAmount: 540000,
      status: "pending",
      canFlag: true,
      canDisburse: true,
      flagReason: null,
      flaggedAt: null,
    },
    {
      disbursementId: 904,
      investorId: 904,
      investmentFundId: 88,
      disbursementCode: "YLD-PNT-105",
      investorName: "Ngozi I.",
      amountInvested: 11000000,
      payoutAmount: 495000,
      status: "disbursed",
      canFlag: false,
      canDisburse: false,
      flagReason: null,
      flaggedAt: null,
    },
    {
      disbursementId: 905,
      investorId: 905,
      investmentFundId: 88,
      disbursementCode: "YLD-PNT-106",
      investorName: "David M.",
      amountInvested: 8000000,
      payoutAmount: 360000,
      status: "flagged",
      canFlag: false,
      canDisburse: false,
      flagReason: "Bank account mismatch",
      flaggedAt: "2026-02-01 11:00",
    },
  ],
};

export function getYieldEventDetailById(eventId: string) {
  return DUMMY_YIELD_EVENT_DETAILS.eventId === eventId
    ? DUMMY_YIELD_EVENT_DETAILS
    : undefined;
}
